### ISSUE TITLE
能说说是怎么实现的吗，大神，小白自学，希望理解里面的原理和操作

### ISSUE THREAD

**Issue by MicroMatrixOrg** [Vitaminaq/vue-rescroll#1]
能说说是怎么实现的吗，大神，小白自学，希望理解里面的原理和操作

**Comment by Vitaminaq** [comment]
https://cn.vuejs.org/v2/guide/custom-directive.html#ad 这是它的官方文档，每个dom节点，跟组件，页面一样，会有一些钩子函数，类似于created这样的，我们就可以在它的不同时期触发的钩子函数去做一些事情

**Comment by MicroMatrixOrg** [comment]
大神，我的项目里面引用你的组件前两天还能用后面就不起作用了，返回不记录位置，没有加keep-alive

**Comment by Vitaminaq** [comment]
你要看下你所绑定的dom节点，是不是有滚动条，如果有，要区分是全局滚动条(window)还是局部的
